// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjdkdGZBpC11LUncxQSpJ7mgXSTy-EeNQ',
    appId: '1:830437057159:web:18ee6e3e1e0a0bf6e24e22',
    messagingSenderId: '830437057159',
    projectId: 'goparent-e474c',
    authDomain: 'goparent-e474c.firebaseapp.com',
    storageBucket: 'goparent-e474c.appspot.com',
    measurementId: 'G-VXLLK8Q3K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBycQRxfgYAEa3NS7CHoIcjv7IfKD4QcaM',
    appId: '1:830437057159:android:568a6d5d92f21bc1e24e22',
    messagingSenderId: '830437057159',
    projectId: 'goparent-e474c',
    storageBucket: 'goparent-e474c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_vU5ihiWVv0x-nflx1XGLULUSQWzFVFs',
    appId: '1:830437057159:ios:39b815fa93a34ccfe24e22',
    messagingSenderId: '830437057159',
    projectId: 'goparent-e474c',
    storageBucket: 'goparent-e474c.appspot.com',
    iosBundleId: 'com.example.goParent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_vU5ihiWVv0x-nflx1XGLULUSQWzFVFs',
    appId: '1:830437057159:ios:39b815fa93a34ccfe24e22',
    messagingSenderId: '830437057159',
    projectId: 'goparent-e474c',
    storageBucket: 'goparent-e474c.appspot.com',
    iosBundleId: 'com.example.goParent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjdkdGZBpC11LUncxQSpJ7mgXSTy-EeNQ',
    appId: '1:830437057159:web:399d767368f6e22be24e22',
    messagingSenderId: '830437057159',
    projectId: 'goparent-e474c',
    authDomain: 'goparent-e474c.firebaseapp.com',
    storageBucket: 'goparent-e474c.appspot.com',
    measurementId: 'G-8WSE18S66F',
  );
}
