name: go_parent
description: "A new Flutter project."
version: 1.0.2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  get: ^4.6.6
  flutter_helper_utils: ^6.6.0
  introduction_screen: ^3.1.14
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.1.2
  intl: ^0.19.0
  bitsdojo_window: ^0.1.6
  rflutter_alert: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  fonts:
    - family: CodeNewRoman
      fonts:
        - asset: assets/fonts/Code New Roman.otf

  assets:
    - assets/images/
    - assets/images/alert_icons/